map_file: "/Users/whitesa3/Projects/AoU_GWAS/map.tsv"
gnomad_ref_dir: "/Users/whitesa3/Projects/GBMI-GWAS/GNOMAD_REF/align_ref"
gnomad_flag_dir: "/Users/whitesa3/Projects/GBMI-GWAS/GNOMAD_REF/flagged_variants"
output_tsv: "output/AoU/results"
output_plots: "output/AoU/plots"
